"""
TauriCPP 资源打包工具
将前端文件打包为Windows资源脚本(.rc)，编译后嵌入exe
运行时通过VirtualFS从内存加载，不产生临时文件

使用数字资源ID + 映射头文件，确保 rc.exe 和 llvm-rc 兼容
"""
import os
import sys
import argparse

def generate_rc(frontend_dir, output_rc, resource_type="TAURI_RES"):
    """扫描前端目录，生成.rc资源脚本和映射头文件"""
    entries = []

    for root, dirs, files in os.walk(frontend_dir):
        for fname in files:
            full_path = os.path.join(root, fname)
            rel_path = os.path.relpath(full_path, frontend_dir)
            res_name = rel_path.replace("\\", "/")
            entries.append((res_name, full_path))

    if not entries:
        print(f"Warning: No files found in {frontend_dir}")
        return

    # 生成映射头文件：数字ID -> 虚拟路径
    header_dir = os.path.dirname(output_rc)
    header_path = os.path.join(header_dir, "resource_ids.h")

    with open(header_path, 'w', encoding='utf-8') as f:
        f.write("// Auto-generated by TauriCPP resource packer\n")
        f.write("// Maps numeric resource IDs to virtual paths\n\n")
        f.write("#pragma once\n\n")
        for i, (res_name, _) in enumerate(entries):
            # C标识符安全的名称
            safe_name = res_name.replace("/", "_").replace(".", "_").replace("-", "_").upper()
            f.write(f'#define RES_{safe_name} {1000 + i}\n')
        f.write(f'\n#define RES_COUNT {len(entries)}\n')

    # 生成.rc文件，使用数字ID
    with open(output_rc, 'w', encoding='utf-8') as f:
        f.write(f"// Auto-generated by TauriCPP resource packer\n")
        f.write(f"// Do not edit manually\n\n")
        f.write(f'#include "resource_ids.h"\n\n')

        for i, (res_name, file_path) in enumerate(entries):
            safe_name = res_name.replace("/", "_").replace(".", "_").replace("-", "_").upper()
            rc_path = file_path.replace("\\", "/")
            f.write(f'RES_{safe_name} {resource_type} "{rc_path}"\n')

    # 生成路径映射C文件，VirtualFS用它来映射数字ID到虚拟路径
    map_path = os.path.join(header_dir, "resource_map.cpp")
    with open(map_path, 'w', encoding='utf-8') as f:
        f.write('// Auto-generated by TauriCPP resource packer\n')
        f.write('#include "tauricpp/virtual_fs.hpp"\n')
        f.write('#include "resource_ids.h"\n')
        f.write('#include <Windows.h>\n\n')
        f.write('namespace tauricpp {\n\n')
        f.write('void VirtualFS::LoadFromResources(HMODULE hModule) {\n')
        for i, (res_name, _) in enumerate(entries):
            safe_name = res_name.replace("/", "_").replace(".", "_").replace("-", "_").upper()
            f.write(f'    {{\n')
            f.write(f'        HRSRC hrsrc = FindResourceW(hModule, MAKEINTRESOURCEW(RES_{safe_name}), L"TAURI_RES");\n')
            f.write(f'        if (hrsrc) {{\n')
            f.write(f'            HGLOBAL hGlobal = LoadResource(hModule, hrsrc);\n')
            f.write(f'            if (hGlobal) {{\n')
            f.write(f'                DWORD size = SizeofResource(hModule, hrsrc);\n')
            f.write(f'                void* data = LockResource(hGlobal);\n')
            f.write(f'                if (data && size > 0) {{\n')
            f.write(f'                    std::vector<uint8_t> fileData(static_cast<const uint8_t*>(data), static_cast<const uint8_t*>(data) + size);\n')
            f.write(f'                    RegisterFile("/{res_name}", fileData, "");\n')
            f.write(f'                }}\n')
            f.write(f'            }}\n')
            f.write(f'        }}\n')
            f.write(f'    }}\n')
        f.write('}\n\n')
        f.write('} // namespace tauricpp\n')

    print(f"Generated {output_rc} with {len(entries)} resources:")
    for name, path in entries:
        print(f"  {name} <- {path}")

def main():
    parser = argparse.ArgumentParser(description="TauriCPP Resource Packer")
    parser.add_argument("frontend_dir", help="Frontend directory to pack")
    parser.add_argument("-o", "--output", default="resources.rc", help="Output .rc file")
    parser.add_argument("-t", "--type", default="TAURI_RES", help="Resource type name")
    args = parser.parse_args()

    if not os.path.isdir(args.frontend_dir):
        print(f"Error: {args.frontend_dir} is not a directory")
        sys.exit(1)

    generate_rc(args.frontend_dir, args.output, args.type)

if __name__ == "__main__":
    main()
